config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/calendar', to: 'calendar#index', as: 'calendar'
  root to: "categories#index"
  resources :categories do
    resources :tasks, shallow: true
    end
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, :details, presence: true, uniqueness: true
  validates :details, length: {maximum: 100}
  belongs_to :user
  has_many :tasks, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord
  validates :action_item, :deadline, :priority, presence: true
  validates :action_item, length: {maximum: 20}
  validates :priority, inclusion: { in: ['Critical','Medium', 'Low', 'Trivial'],
    message: "%{value} is not a valid priority level, valid levels are Blocker, Critical, Medium, Low and Trivial" }
  validate :is_deadline_valid
  belongs_to :category
  belongs_to :user

  def is_deadline_valid
    if deadline != nil
      if deadline < Date.today
        errors.add(:deadline, 'cannot be past date')
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :first_name, :last_name, :time_zone, presence: true
  validates :email, uniqueness: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories, dependent: :destroy
  has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
     before_action :authenticate_user!
     before_action :configure_permitted_parameters, if: :devise_controller?
     around_action :set_time_zone, if: :current_user
     
     private

     def set_time_zone(&block)
     Time.use_zone(current_user.time_zone, &block)
     end

     protected

          def configure_permitted_parameters
               devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :time_zone, :email, :password)}

               devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password, :current_password, :password_confirmation, :time_zone)}
          end

end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
    
    def index
        @tasks = Task.where "user_id = ?", current_user.id
        @tasks_today = @tasks.where "deadline = ?", Date.current
        @tasks_tomorrow = @tasks.where "deadline = ?", Date.tomorrow


        @tasks_this_week = @tasks.where "deadline = ?", Date.today.beginning_of_week...Date.today.end_of_week

        @tasks_this_month = @tasks.where "deadline = ?",Date.today.beginning_of_month...Date.today.end_of_month
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    
    def index
        @categories = current_user.categories
    end
    
    def show
        @current_user_categories = current_user.categories
        @category = @current_user_categories.find params[:id]
    end

    def new
        @category = current_user.categories.build
    end

    def create
        @category = current_user.categories.build(category_params)
        respond_to do |format|
            if  @category.save
                format.html { redirect_to category_path(@category), notice: "Category was successfully created!." }
            else
                format.html { render :new, status: :unprocessable_entity }
            end
        end
    end

    def edit
        @category = Category.find params[:id]
    end

    def update
        @category = Category.find params[:id]
        respond_to do |format|
            if @category.update(category_update_params)
                format.html { redirect_to category_path(@category), notice: "Category was successfully updated!." }
            else
                format.html { render :edit, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        @category = Category.find params[:id]
        @category.destroy
            respond_to do |format|
                format.html { redirect_to '/categories', notice: "Category was successfully deleted!" }
            end
    end

    private
    
    def set_category
        @category = Category.find params[:id]
    end

    def category_params
        params.require(:category).permit(:title, :details)
    end

    def category_update_params
        params.require(:category).permit(:title, :details)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @name = current_user.present? ? current_user.first_name : 'Stranger'
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :set_task, only: %i[ show edit update destroy ]
    before_action :set_category, only: %i[ new create ]

    def index
    end
    
    def new
        @task = @category.tasks.build(user_id: current_user.id)
    end
        
    def create
        @task = @category.tasks.build(task_params.merge(user_id: current_user.id))
        respond_to do |format|
            if  @task.save
                format.html { redirect_to task_path(@task), notice: "Task was successfully created!." }
            else
                format.html { render :new, status: :unprocessable_entity }
            end
        end
    end

    def show
    @current_user_categories = current_user.tasks
    end
    
    def edit
    end

    def update
        respond_to do |format|
            if @task.update(task_update_params)
                format.html { redirect_to task_path(@task), notice: "Task was successfully updated!." }
            else
                format.html { render :edit, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        @task.destroy
            respond_to do |format|
                format.html { redirect_to '/categories', notice: "Task was successfully deleted!" }
            end
    end

    private

    def set_task
        @task = current_user.tasks.find params[:id]
    end

    def set_category
        @category = Category.find params[:category_id]
    end

    def task_params 
        params.require(:task).permit(:action_item, :deadline, :priority, :user_id)
    end

    def task_update_params
        params.require(:task).permit(:action_item, :deadline, :priority)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/calendar/index.html.erb
<h1><%= Time.now.in_time_zone(current_user.time_zone) %></h1>

<span>Action Item</span> | <span>Priority</span> |<span>Created At</span> | <span>Deadline</span><br>
<% @tasks_today.each do |t| %>
<%=t.action_item%> | <%=t.priority%> | <%=t.created_at.to_date%> | <%=t.deadline%><br> <%=Date.current.in_time_zone(current_user.time_zone)%>
<%end%>


<%= @tasks_tomorrow.each do |t|%>
    <%=t.action_item%>
<%end%>


<%=  @tasks_this_week.each do |t|%>
    <%=t.action_item%>
<%end%>

<%=  @tasks_this_month.each do |t| %>
    <%=t.action_item%>
<%end%>

app/views/categories/_editform.html.erb
<% if @category.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@category.errors.count, "error") %> prohibited this article from being saved:</h2>

    <ul>
      <% @category.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<div class='registration_right'>
  <div class ='registration_form'>
    <%= form_with model: @category, url: category_path, method: :patch do |form| %>
      <p>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
      </p>
      <p>
        <%= form.label :details %><br>
        <%= form.text_field :details %>
      </p>
      <p>
        <%= form.submit %>
      </p>
    <% end %>
  </div>
</div>

app/views/categories/_form.html.erb
<% if @category.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@category.errors.count, "error") %> prohibited this article from being saved:</h2>

    <ul>
      <% @category.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<div class='registration_right'>
    <div class ='registration_form'>
      <%= form_with model: [@category ] do |form| %>
        <p>
          <%= form.label :title %><br>
          <%= form.text_field :title %>
        </p>
        <p>
          <%= form.label :details %><br>
          <%= form.text_field :details %>
        </p>
        <p>
          <%= form.submit %>
        </p>
      <% end %>
    </div>
  </div>

app/views/categories/edit.html.erb
<h2>Edit a category:</h2>

<%= render 'editform' %>
<%= link_to 'My Dashboard', categories_path %>

app/views/categories/index.html.erb
<div class='dashboard_page'>

<h1>Welcome, <%= current_user.first_name.downcase.capitalize%>!</h1>
<div class="new_category">
        <%= link_to new_category_path do %>
             <i class="fa fa-plus-square-o"></i> New Category
        <% end %>
</div>
        <div class="card_grid_container">
    <% @categories.each do |c| %>
        <div class="cards">
            <div class="category_links">
                <div class="category_title">
                    <%= link_to c.title, category_path(c.id)%>
                    <span id="task_count"><%= c.tasks.count%></span>
                </div>
                <div class="dropdowna">
                    <button class="dropbtna"><i class="fa fa-caret-square-o-down"></i></button>
                    <div class="dropdown-contenta">
                    <%= link_to edit_category_path(c.id) do %>
                        <i class="fa fa-pencil-square-o"></i> Update Category
                    <% end %>
                    <%= link_to category_path(c.id), method: :delete, data: {confirm: 'Are you sure?'} do %>
                        <i class="fa fa-ellipsis-h"></i> Delete Category
                    <% end %>
                    </div>
                </div>

            </div>        
            <div class="category_container">
                        <% c.tasks.each do |t| %>
                            <div class="task_container">
                                <div class="task_upper">
                                    <div class="action_item">
                                        <%= link_to t.action_item, task_path(t.id)%>
                                    </div>
                                    <div class="dropdowna">
                                            <button class="dropbtna"><i class="fa fa-ellipsis-h"></i></button>
                                            <div class="dropdown-contenta">
                                            <%= link_to edit_task_path(t.id) do %>
                                                <i class="fa fa-pencil-square-o"></i> Update Task
                                            <% end %>
                                            <%= link_to task_path(t.id), method: :delete, data: {confirm: 'Are you sure?'} do %>
                                                <i class="fa fa-ellipsis-h"></i> Delete Task
                                            <% end %>
                                            </div>
                                    </div>
                                </div>
                                <div class="deadline_actions">
                                    <div class="deadline">
                                        <p><%= t.deadline.strftime('%a, %b %d')%></p>
                                        <p><%= t.priority%></p>
                                    </div>
                                    
                                </div>
                            </div>
                        <%end%>
                        <%= link_to new_category_task_path(c.id) do %>
                            <i class="fa fa-plus-square-o"></i> New Task
                        <% end %>


                        
                        	
            </div>

        </div>
    <%end%>
    </div>
</div>

app/views/categories/new.html.erb
<p><%= current_user%></p>
<h2>Add a category:</h2>

<%= render 'form' %>

app/views/categories/show.html.erb
<%= @category.title%>
<%= @category.details%>

<%= link_to 'My Dashboard', categories_path %>
<%= link_to 'New Task', new_category_task_path(@category.id) %>

app/views/home/index.html.erb
<h1>Welcome, <%= @name%>!</h1>
<h2>Current Tmezone :<%= current_user.time_zone %></h2>
    <% if user_signed_in? %>
        <%= link_to 'My Dashboard', categories_path %>
        <%= link_to 'Calendar', calendar_path %>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KanbanApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="topnav">
    <span>My Logo</span>

    <% if user_signed_in? %>
        <%= link_to 'Home', '/' %>
    <% end %>
    
    <div class="dropdown">
        <button class="dropbtn">Resources</button>
        <div class="dropdown-content">
            <a>Documentation</a>
            <a>Add more after...</a>
        </div>
    </div>


    <% if user_signed_in? %>
    <%= link_to 'Calendar', calendar_path %>
    <%= link_to 'Dashboard', categories_path %>
    <div class="dropdown">
        <button class="dropbtn">Account make user avatar</button>
        <div class="dropdown-content">
            <%= link_to 'Update User Details', edit_user_registration_path %>
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
        </div>
    </div>
    <% else %>
    
    <div class="dropdown">
        <button class="dropbtn">Features</button>
        <div class="dropdown-content">
            <a>Dashboard</a>
            <a>Add more after...</a>
        </div>
    </div>

        <%= link_to 'Sign In', new_user_session_path %>
        <%= link_to 'Get Started', new_user_registration_path %>
    <% end %>

</div>

app/views/tasks/edit.html.erb
<h2>Edit <%= @task.action_item%></h2>

<% if @task.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@task.errors.count, "error") %> prohibited this article from being saved:</h2>

    <ul>
      <% @task.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

 <div class='registration_right'>
  <div class ='registration_form'>
  <%= form_with model: @task, url: task_path, method: :patch do |form| %>
  <p>
    <%= form.label :action_item %><br>
    <%= form.text_field :action_item %>
  </p>
  <p>
    <%= form.label :priority %><br>
    <%= form.select(:priority, options_for_select([["Critical"],["Medium"],["Trivial"]])) %>
  </p>
  <p>
    <%= form.label :deadline %><br>
    <%= form.date_field :deadline  %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>
</div>
</div>
  <%= link_to 'My Dashboard', categories_path %>

app/views/tasks/new.html.erb
<h2>Add a task</h2>


<% if @task.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@task.errors.count, "error") %> prohibited this article from being saved:</h2>

    <ul>
      <% @task.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


 <div class='registration_right'>
  <div class ='registration_form'>
<%= form_with model: [@category, @task ] do |form| %>
  <p>
    <%= form.label :action_item %><br>
    <%= form.text_field :action_item %>
  </p>
  <p>
    <%= form.label :urgency %><br>
    <%= form.select(:priority, options_for_select([["Critical"],["Medium"],["Trivial"]])) %>
  </p>
  <p>
    <%= form.label :deadline %><br>
    <%= form.date_field :deadline %>
  </p>
  <p>
    <%= form.submit %>
  </p>
  </div>
  </div>
<% end %>

app/views/tasks/show.html.erb
<%= @task.action_item%>
<%= @task.priority%>
<%= @task.deadline%>


<%= link_to 'My Dashboard', categories_path %>